Repository greenpeace/planet4-plugin-blocks, pull requests merged in 2019-04, with the labels that each got.

#520 Fixes issue with timeline preview iframe not having css if the post h…
  assets/scss/components/_timeline.scss
  classes/controller/blocks/class-timeline-controller.php
  style.css
  style.css.map
Labels: Review & Merge

#522 Bug/planet 3376 publications link are empty
  classes/controller/blocks/class-newcovers-controller.php
Labels: Hotfix, Review & Merge

#519 PLANET-3346: Gallery Block, Three columns style: Uses full images instead of thumbnails
  classes/controller/blocks/class-gallery-controller.php
  includes/blocks/gallery.twig
Labels: Review & Merge

#521 PLANET-3372 Added report for different carousel header styles
  planet4-blocks.php
Labels: Review & Merge

#523 Carousel Header: Truncate 32 chars instead of 30 in twig (no JIRA issue)
  includes/blocks/carousel_header_full-width-classic.twig
Labels: Review & Merge

#525 PLANET-3379: Break down the blocks.css of the campaigns site to smaller parts
  assets/scss/base/_blocks.scss
  assets/scss/campaigns/block-overrides/_campaign_articles.scss
  assets/scss/campaigns/block-overrides/_campaign_carousel.scss
  assets/scss/campaigns/block-overrides/_campaign_content_four_column.scss
  assets/scss/campaigns/block-overrides/_campaign_content_three_column.scss
  assets/scss/campaigns/block-overrides/_campaign_content_two_columns.scss
  assets/scss/campaigns/block-overrides/_campaign_covers.scss
  assets/scss/campaigns/block-overrides/_campaign_happy_point.scss
  assets/scss/campaigns/block-overrides/_campaign_split_two_columns.scss
  assets/scss/campaigns/block-overrides/_campaign_static_four_column.scss
  assets/scss/campaigns/block-overrides/_campaign_submenu.scss
  assets/scss/campaigns/block-overrides/_campaign_tasks.scss
  assets/scss/campaigns/components/_campaign_thumbnail.scss
  assets/scss/campaigns/components/_campaign_video.scss
  assets/scss/campaigns/themes/_theme_antarctic.scss
  assets/scss/campaigns/themes/_theme_arctic.scss
  assets/scss/campaigns/themes/_theme_forest.scss
  assets/scss/campaigns/themes/_theme_oceans.scss
  assets/scss/campaigns/themes/_theme_oil.scss
  assets/scss/campaigns/themes/_theme_plastic.scss
  assets/scss/global/_blocks.scss
  assets/scss/style.scss
  package-lock.json
  style.css
  style.css.map
Labels: Review & Merge

#527 Testing in PHP 7.3
  .circleci/config.yml
Labels: Review but NOT MERGE

#529 PLANET-3398: CPP - Fix Secondary button colors across all blocks
  includes/blocks/split_two_columns.twig
Labels: Review & Merge

#528 PLANET-3387 CPP - Fix Take action block button color
  assets/scss/campaigns/block-overrides/_campaign_covers.scss
  style.css
  style.css.map
Labels: Review & Merge

#531 PLANET-3417 fix cover card scrolling
  assets/js/partials/post_action.js
  main.js
  main.js.map
Labels: Review & Merge

#530 PLANET-3380 admin convert blocks
  classes/class-loader.php
  classes/controller/menu/class-blocks-usage-controller.php
  classes/controller/menu/class-settings-controller.php
  includes/settings.twig
  planet4-blocks.php
  vendor/composer/ClassLoader.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: Review & Merge

#535 PLANET-3380 admin convert blocks 2
  planet4-blocks.php
Labels: Review & Merge

#533 PLANET-3422: Main content in Campaign pages is attached to the bottom of the browser.
  assets/scss/base/_blocks.scss
  assets/scss/base/_mixins.scss
  assets/scss/campaigns/themes/_theme_oil.scss
  assets/scss/style.scss
  style.css
  style.css.map
Labels: Review & Merge

#536 PLANET-3431 restructure commands code
  classes/class-loader.php
  classes/command/class-controller.php
  planet4-blocks.php
  vendor/composer/autoload_classmap.php
  vendor/composer/autoload_static.php
Labels: Review & Merge

#532 PLANET-3418 - Add Campaigns overrides for the Columns block
  assets/scss/campaigns/block-overrides/_campaign_columns.scss
  assets/scss/campaigns/block-overrides/_campaign_content_two_columns.scss
  assets/scss/campaigns/block-overrides/_campaign_static_four_column.scss
  assets/scss/campaigns/themes/_theme_antarctic.scss
  assets/scss/campaigns/themes/_theme_arctic.scss
  assets/scss/campaigns/themes/_theme_forest.scss
  assets/scss/campaigns/themes/_theme_oceans.scss
  assets/scss/campaigns/themes/_theme_oil.scss
  assets/scss/campaigns/themes/_theme_plastic.scss
  assets/scss/style.scss
  style.css
  style.css.map
Labels: Review & Merge

#534 PLANET-3423: White gradient in campaign pages becomes grey in safari.
  assets/scss/base/_variables.scss
  assets/scss/campaigns/themes/_theme_antarctic.scss
  assets/scss/campaigns/themes/_theme_arctic.scss
  assets/scss/campaigns/themes/_theme_forest.scss
  assets/scss/campaigns/themes/_theme_oceans.scss
  style.css
  style.css.map
Labels: Review & Merge

#537 PLANET-3383: CPP - Carousel block resizing based on caption length
  assets/scss/campaigns/block-overrides/_campaign_carousel.scss
  style.css
  style.css.map
Labels: Review & Merge

#538 PLANET-3418 - Campaigns: Columns CTA arrows fix overlapping
  assets/scss/campaigns/block-overrides/_campaign_columns.scss
  assets/scss/campaigns/themes/_theme_antarctic.scss
  style.css
  style.css.map
Labels: Review & Merge

#539 PLANET-3418 - Campaigns: Make CTA arrow more consistent
  assets/scss/base/_mixins.scss
  assets/scss/campaigns/block-overrides/_campaign_columns.scss
  assets/scss/campaigns/block-overrides/_campaign_submenu.scss
  assets/scss/campaigns/themes/_theme_antarctic.scss
  assets/scss/campaigns/themes/_theme_forest.scss
  style.css
  style.css.map
Labels: Review & Merge

#540 PLANET-3442 - Timeline: Force full width on content
  assets/scss/components/_timeline.scss
  style.css
  style.css.map
Labels: Review & Merge

#541 PLANET-3467 Submenu block: problems with styles
  assets/scss/components/_submenu.scss
  includes/blocks/submenu.twig
  style.css
  style.css.map
Labels: Review & Merge

#543 PLANET-3347: #375896 having multiple carousels in a post some may seem unresponsive to manual scroll
  classes/controller/blocks/class-carousel-controller.php
  classes/controller/blocks/class-gallery-controller.php
Labels: Review & Merge

#542 PLANET-3434: #379215 Timeline block: Description text should use Lora font
  assets/scss/components/_timeline.scss
  style.css
  style.css.map
Labels: Review & Merge

#545 PLANET-3506 The wp object $action that we use already has the excerpt
  classes/controller/blocks/class-covers-controller.php
  classes/controller/blocks/class-newcovers-controller.php
Labels: Review & Merge

#546 PLANET-3508 - Remove button class from Split Two Column CTA
  includes/blocks/split_two_columns.twig
Labels: Review & Merge
